/*  Consider the following algorithm
    Start with a positive number n
    if n is even then divide by 2if n is odd then multiply by 3 and add 1
    continue this until n becomes 1
    The Guthrie sequence of a positive number n is defined to be the numbers generated by the
    above algorithm.
    For example, the Guthrie sequence of the number 7 is
    7, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1
    It is easy to see that this sequence was generated from the number 7 by the above algorithm.
    Since 7 is odd multiply by 3 and add 1 to get 22 which is the second number of the sequence.
    Since 22 is even, divide by 2 to get 11 which is the third number of the sequence. 11 is odd so
    multiply by 3 and add 1 to get 34 which is the fourth number of the sequence and so on.
    Note: the first number of a Guthrie sequence is always the number that generated the sequence
    and the last number is always 1.
    Write a function named isGuthrieSequence which returns 1 if the elements of the array form a
    Guthrie sequence. Otherwise, it returns 0.
    If you are programming in Java or C#, the function signature is
    int isGuthrieSequence(int[ ]
*/

public class Main {

    public static void main(String[] args) {
        int[] arr1 = {-8,4,2,1}; //output 1
        int[] arr2 = {8,4,1}; //output 0
        int[] arr3 = {7, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1}; //output 1

        System.out.println(isGuthrieSequence(arr1)); //output 1
        System.out.println(isGuthrieSequence(arr2)); //output 0
        System.out.println(isGuthrieSequence(arr3)); //output 1
    }

    public static int isGuthrieSequence(int[] a) {
        
        int num = a[0];

        if(num <=0 || a[a.length -1] != 1 ){
            return 0;
        }

        for(int i = 1; i<a.length; i++) {
        
            if(num == 1) {
                break;
            }
            if(num % 2 == 0) {
                num = num / 2;
            }else{
                num = (num * 3) + 1;
            }

            if(num != a[i]) {
                return 0;
            }
        }
       return 1;
    }
}

